// <auto-generated />
using EFInheritance.Lib.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFInheritance.Lib.Migrations.Tpt
{
    [DbContext(typeof(TptContext))]
    partial class TptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFInheritance.Lib.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EFInheritance.Lib.Models.Cat", b =>
                {
                    b.HasBaseType("EFInheritance.Lib.Models.Animal");

                    b.Property<string>("Sound")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Cats");
                });

            modelBuilder.Entity("EFInheritance.Lib.Models.Dog", b =>
                {
                    b.HasBaseType("EFInheritance.Lib.Models.Animal");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("EFInheritance.Lib.Models.Cat", b =>
                {
                    b.HasOne("EFInheritance.Lib.Models.Animal", null)
                        .WithOne()
                        .HasForeignKey("EFInheritance.Lib.Models.Cat", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFInheritance.Lib.Models.Dog", b =>
                {
                    b.HasOne("EFInheritance.Lib.Models.Animal", null)
                        .WithOne()
                        .HasForeignKey("EFInheritance.Lib.Models.Dog", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
